# Introduction: basic Julia usage and plotting

This lecture is an updated and improved version of the highly-viewed ["Julia Zero2Hero" workshop](https://www.youtube.com/watch?v=Fi7Pf2NveH0). The new version includes a dedicated block about plotting, provides simpler explanations, is updated to the newest Julia versions, and has more accessible exercises!

This lecture is also used as the first lecture in a full course series called [**Nonlinear Dynamics and Complex Systems analysis with Julia**](https://github.com/JuliaDynamics/NonlinearDynamicsComplexSystemsCourse)!

## Why should I learn Julia?


[Julia](https://julialang.org/) is a relatively new programming language, developed at MIT, with version 1.0 released in August 2018. Even though it is so recent, it has taken the scientific community by storm and many serious large scale projects have started using Julia.

The [Julia documentation](https://docs.julialang.org/en/v1/) outlines the main facts and features of Julia. I have summarized my opinions on why Julia is the best choice for scientific computing in this [GitHub page](https://github.com/Datseris/whyjulia-manifesto).

# Basics of Julia

In this block we will overview basic Julia syntax, data structures, iteration, and using functions. The block assumes familiarity with programming, in the sense of reasoning about code, and also familiarity with the concept of an interactive development environment (or dynamic programming languages) where a program may be written and executed interactively line-by-line. The block doesn't assume any familiarity with a specific programming language however.

## Basic syntax


### Assignment

Assignment of variables in Julia is done with the `=` sign.

In [1]:
x = 1

1

In [2]:
x

1

You can assign *anything* to a variable binding. This includes functions, modules, data types, or whatever you can come up with.

Variable names can include practically any Unicode character. Additionally, most Julia editing environments offer "LaTeX Completion". Pressing e.g. `\delta` and then TAB will create the corresponding Unicode character using the LaTeX syntax.

In [3]:
δ = 4 # type `\delta` and then press tab!

4

You can assign multiple variables to multiple values using commas.

In [4]:
a, b, 😺 = 1, 0, -1

(1, 0, -1)

Strings are created between double quotes `"` while the single quotes `'` are used for characters only.

In [5]:
welcome = "Karibu Kenya!"

"Karibu Kenya!"

In [6]:
char = '안' # for characters, Julia prints their Unicode information

'안': Unicode U+C548 (category Lo: Letter, other)

Since assignment returns the value, by default this value is printed. This is **AMAZING**, but you can also silence printing by adding `;` to the end of the expression:

In [7]:
x = 3;

Lastly, you can interpolate any expression into a string using `$(expression)`

In [8]:
"the value of the cat face (😺) is $(😺)"

"the value of the cat face (😺) is -1"

In [9]:
"I am doing math inside a string: $(π^2 - x)"

"I am doing math inside a string: 6.869604401089358"

### Math operations

Basic math operators are `+, -, *, /` and `^` for power.

In [10]:
x = 3
y = x^2.6

17.398638404385867

Most julia operators have their `=` version, which updates something with its own value

In [11]:
x += 3 # x = x + 3
x -= 3
x *= 2
x /= 2

3.0

Literal numbers can multiply anything without having to put `*` inbetween, as long as the number is on the left side:

In [12]:
5x - 12.54y * 1.2e-5x

14.992145558678724

## Type basics

Everything that exists in Julia has a certain **Type**. (e.g. numbers can be integers, floats, rationals). This "type system" is instrumental for the inner workings of Julia, and is mainly what enables Julia to have performance matching static languages like C.

The type system also enables **Multiple Dispatch**, one of Julia's greatest features, which we will cover in the second lecture.

To find the type of a thing in Julia you simply use `typeof(thing)`:

In [13]:
x = 3
typeof(x)

Int64

In [14]:
typeof(1.5)

Float64

In [15]:
typeof(1.5f0)

Float32

In [16]:
typeof("asdf")

String

## Basic collection datastructures

Indexing a collection (like an array or a dictionary) in Julia is done with brackets: `collection[index]`.

In **ordered collections** (where the elements are specified by their order rather than some key), indexing is done using the positive integers. This means that **indexing in Julia starts from 1, which is exceptionally good,** because the index matches the element order: the 5th element has index 5.


### Tuples
Tuples are **immutable ordered collections** of elements of any type. They are most useful when the elements are not of the same type with each other and are intended only for small collections.

Syntax:

```julia
(item1, item2, ...)
```

In [17]:
myfavoritethings = ("purple", '🥁', π)

("purple", '🥁', π)

In [18]:
myfavoritethings[1]

"purple"

You can extract multiple values into variables from any collection using commas.

In [19]:
a, b, c = myfavoritethings
c

π = 3.1415926535897...

The type of the tuple is the type of its constituents.

In [20]:
typeof(myfavoritethings)

Tuple{String, Char, Irrational{:π}}

Dictionaries have a specific type for keys and values. First type is the type of key, second is the type of value.

### Named tuples

These are exactly like tuples but also assign a name to each variable they contain.
Hence, they are an **immutable collection of ordered _and_ named elements**. 
They rest between the `Tuple` and `Dict` type in their use.
Using NamedTuples can be very convenient because it makes for more readable code but provides the same speed as Tuples.

Their syntax is:
```julia
(key1 = val1, key2 = val2, ...)
```
For example:

In [21]:
nt = (x = 5, y = "str", z = 5/3)

(x = 5, y = "str", z = 1.6666666666666667)

These objects can be accessed with `[1]` like normal tuples, but also with the syntax `.key`:

In [22]:
nt[1]

5

In [23]:
nt.x # equivalent with nt[:x]

5

(named tuples are useful to know, because keyword arguments to functions are essentially named tuples)

### Arrays

The standard Julia `Array` is a **mutable and ordered collection of items of the same type**.
The dimensionality of the Julia array is important. A `Matrix` is an array of dimension 2. A `Vector` is an array of dimension 1. The *element type* of what an array contains is irrelevant to its dimension!

**i.e. a Vector of Vectors of Numbers and a Matrix of Numbers are two totally different things!**

The syntax to make a vector is enclosing elements in brackets:

In [24]:
fibonacci = [1, 1, 2, 3, 5, 8, 13]

7-element Vector{Int64}:
  1
  1
  2
  3
  5
  8
 13

Arrays of other data structures, e.g. vectors or dictionaries, or anything, as well as multi-dimensional arrays are possible:

In [25]:
vec_vec_num = [[1, 2, 3], [4, 5], [6, 7, 8, 9]] # vector of vectors, which is NOT a matrix

3-element Vector{Vector{Int64}}:
 [1, 2, 3]
 [4, 5]
 [6, 7, 8, 9]

If you want to make a matrix, two ways are the most common: (1) specify each entry one by one

In [26]:
matrix = [1 2 3; # elements in same row separated by space
          4 5 6; # semicolon means "go to next row"
          7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

or (2), you use a function that initializes a matrix. E.g. `rand(n, m)` will create an `n×m` matrix with uniformly random numbers

In [27]:
R = rand(4, 3)

4×3 Matrix{Float64}:
 0.360213  0.89702    0.205206
 0.652773  0.0322981  0.112156
 0.951173  0.776246   0.457053
 0.522733  0.943565   0.498062

Like everything in Julia, Arrays use 1-based indexing. You can get the value of an Array by typing each index separated by a comma.

In [28]:
R[1, 2] # two dimensional indexing

0.8970201678690928

Since arrays are mutable we can change their entries _in-place_ (i.e., without creating a new array):

In [29]:
fibonacci = [1, 1, 2, 3, 5, 8, 13]
fibonacci[1] = 15
fibonacci

7-element Vector{Int64}:
 15
  1
  2
  3
  5
  8
 13

We can add or remove elements from any mutable collection with functions like `push!, pop!, delete!`. We'll cover functions in more detail in a moment!

In [30]:
push!(fibonacci, 21)

8-element Vector{Int64}:
 15
  1
  2
  3
  5
  8
 13
 21

Lastly, for multidimensional arrays, the `:` symbol is useful, which means to "select all elements in this dimension".

In [31]:
x = rand(3, 3)

3×3 Matrix{Float64}:
 0.287754   0.686449   0.843921
 0.518753   0.0919105  0.482395
 0.0485356  0.609538   0.80212

In [32]:
x[:, 1] # it means to select the first column

3-element Vector{Float64}:
 0.2877536219260931
 0.518752958863525
 0.04853557534263275

### Ranges
Ranges are useful shorthand notations that define a "vector" (one dimensional array) with equi-spaced entries. They are created with the following syntax:
```julia
start:stop # mainly for integers
start:step:stop
range(start, stop, length)
range(start, stop; step = ...)
```

In [33]:
r = 0:0.01:5

0.0:0.01:5.0

Ranges always include the first element and step until they _do not exceed_ the ending element. If possible, they include the stop element (as above).

In [34]:
r[end-3] # use `end` as index for the final element

4.97

Ranges are not unique to numeric data, and can be used with anything that extends their interface, e.g.

In [35]:
letterrange = 'a':'z'

'a':1:'z'

As ranges are printed in this short form, to see all their elements you can use `collect`, to transform the range into a `Vector`.

In [36]:
collect(letterrange)

26-element Vector{Char}:
 'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
 'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)
 'c': ASCII/Unicode U+0063 (category Ll: Letter, lowercase)
 'd': ASCII/Unicode U+0064 (category Ll: Letter, lowercase)
 'e': ASCII/Unicode U+0065 (category Ll: Letter, lowercase)
 'f': ASCII/Unicode U+0066 (category Ll: Letter, lowercase)
 'g': ASCII/Unicode U+0067 (category Ll: Letter, lowercase)
 'h': ASCII/Unicode U+0068 (category Ll: Letter, lowercase)
 'i': ASCII/Unicode U+0069 (category Ll: Letter, lowercase)
 'j': ASCII/Unicode U+006A (category Ll: Letter, lowercase)
 ⋮
 'r': ASCII/Unicode U+0072 (category Ll: Letter, lowercase)
 's': ASCII/Unicode U+0073 (category Ll: Letter, lowercase)
 't': ASCII/Unicode U+0074 (category Ll: Letter, lowercase)
 'u': ASCII/Unicode U+0075 (category Ll: Letter, lowercase)
 'v': ASCII/Unicode U+0076 (category Ll: Letter, lowercase)
 'w': ASCII/Unicode U+0077 (category Ll: Letter, lowercase)
 'x': ASCII/

Ranges are cool because they **do not store all elements in memory** like `Vector`s. Instead they produce the elements on the fly when necessary, and therefore are in general preferred over `Vector`s if the data is equi-spaced. 

Lastly, ranges are typically used to index into arrays. One can type `A[1:3]` to get the first 3 elements of `A`, or `A[end-2:end]` to get the last three elements of `A`. If `A` is multidimensional, the same type of indexing can be done for any dimension:

In [37]:
A = rand(4, 4)

4×4 Matrix{Float64}:
 0.00678937  0.542829  0.0228061  0.248684
 0.311167    0.626088  0.454104   0.872867
 0.274206    0.606384  0.617596   0.701096
 0.985281    0.5037    0.163937   0.922068

In [38]:
A[1:3, 1]

3-element Vector{Float64}:
 0.006789365159509897
 0.3111671918749933
 0.2742060140444864

In [39]:
A[1:3, 1:3]

3×3 Matrix{Float64}:
 0.00678937  0.542829  0.0228061
 0.311167    0.626088  0.454104
 0.274206    0.606384  0.617596

## Iteration
Iteration in Julia is high-level. This means that not only it has an intuitive and simple syntax, but also iteration works with anything that can be iterated. Iteration can also be extended (more on that later).


### `for` loops

A `for` loop iterates over a container and executes a piece of code, until the iteration has gone through all the elements of the container. The syntax for a `for` loop is

```julia
for *var(s)* in *loop iterable*
    *loop body*
end
```

*you will notice that all Julia code-blocks end with `end`*

In [40]:
for n in 1:5
    println(n)
end

1
2
3
4
5


In the context of `for`  loops, the `enumerate` iterator is often useful. It takes in an iterable and returns pairs of the index and the iterable value. 

In [43]:
for (i, v) in enumerate(rand(3))
    println("value of index $(i): $(v)")
end

value of index 1: 0.5055851613625609
value of index 2: 0.2836996290417967
value of index 3: 0.8215000279209689



## Conditionals

Conditionals execute a specific code block depending on what is the outcome of a given boolean check. 
The  `&, |` are the boolean `and, or` operators.

### `if` block

In Julia, the syntax

```julia
if *condition 1*
    *option 1*
elseif *condition 2*
    *option 2*
else
    *option 3*
end
```

evaluates the conditions sequentially and executes the code-block of the first true condition.

In [44]:
x, y = 5, 6
if x > y
    x
else
    y
end

6

### Ternary operator

The ternary operator (named for having three arguments) is a convenience syntax for small `if` blocks with only two clauses. 

Specifically, the syntax

```julia
condition ? if_true : if_false
```

is syntactically equivalent to

```julia
if condition
    if_true
else
    if_false
end
```

For example

In [45]:
5 == 5.0 ? "yes" : "no"

"yes"

### List comprehension
The list comprehension syntax 
```julia
[expression(a) for a in collection if condition(a)]
```
is available as a convenience way to make a `Vector`. The `if` part is optional.

In [46]:
[    a^2 for a in 1:10 if iseven(a)      ]

5-element Vector{Int64}:
   4
  16
  36
  64
 100

## Functions
Functions are the bread and butter of Julia, which heavily supports functional programming.


### Function declaration

Functions are declared with two ways. First, the verbose

In [47]:
function f(x)
    # function body
    return x^2 # While `return` is not necessary, it is recommended for clarity
end

f (generic function with 1 method)

Or, you can define functions with the short form (best used for functions that only take up a single line of code)

In [48]:
f(x) = x^2  # equivalent with above

f (generic function with 1 method)

Functions are called using their name and parenthesis `()` enclosing the calling arguments:

In [49]:
f(5)

25

Functions in Julia support optional positional arguments, as well as keyword arguments. The **positional** arguments are **always given by their order**, while **keyword** arguments are **always given by their keyword**. Keyword arguments are all the arguments defined in a function after the symbol `;`. Example:

In [50]:
function g(x, y = 5; z = 2, w = 1)
    return x*z*y*w
end

g (generic function with 2 methods)

In [51]:
g(5) # give x. default y, z

50

In [52]:
g(5, 3) # give x, y. default z

30

In [53]:
g(5; z = 3) # give x, z. default y

75

In [54]:
g(2, 4; w = 0.1, z = 1.5) # give everything

1.2000000000000002

In [55]:
g(2, 4, 2) # keyword arguments can't be specified by position

MethodError: MethodError: no method matching g(::Int64, ::Int64, ::Int64)
The function `g` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  g(::Any, ::Any; z, w)
   @ Main c:\Users\tsh371\Documents\julia-workshop\jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y205sZmlsZQ==.jl:1
  g(::Any; ...)
   @ Main c:\Users\tsh371\Documents\julia-workshop\jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y205sZmlsZQ==.jl:1


###  Passing by reference: mutating vs. non-mutating functions

You can divide Julia variables into two categories: **mutable** and **immutable**. Mutable means that the values of your data can be changed in-place, i.e. literally in the place in memory the variable is stored in the computer. Immutable data cannot be changed after creation, and thus the only way to change part of immutable data is to actually make a brand new immutable object from scratch. Use `isimmutable(v)` to check if value `v` is immutable or not.

For example, `Vector`s are mutable in Julia:

In [56]:
x = [5, 5, 5]
x[1] = 6 # change first entry of x
x

3-element Vector{Int64}:
 6
 5
 5

But e.g. `Tuple`s are immutable:

In [57]:
x = (5, 5, 5)
x[1] = 6

MethodError: MethodError: no method matching setindex!(::Tuple{Int64, Int64, Int64}, ::Int64, ::Int64)
The function `setindex!` exists, but no method is defined for this combination of argument types.

In [58]:
x = (6, 5, 5)

(6, 5, 5)

Julia **passes values by reference**. This means that if a mutable object is given to a function, and this object is mutated inside the function, the final result is kept at the passed object. E.g.:

In [59]:
function add3!(x)
    x[1] += 3
    return x
end

x = [5, 5, 5]
add3!(x)
x

3-element Vector{Int64}:
 8
 5
 5

**By convention**, functions with name ending in `!` alter their (mutable) arguments and functions lacking `!` do not. Typically the first argument of a function that ends in `!` is mutated.

For example, let's look at the difference between `sort` and `sort!`.

In [60]:
v = [3, 5, 2]

3-element Vector{Int64}:
 3
 5
 2

In [61]:
sort(v)

3-element Vector{Int64}:
 2
 3
 5

In [62]:
v

3-element Vector{Int64}:
 3
 5
 2

`sort(v)` returns a sorted array that contains the same elements as `v`, but `v` is left unchanged. <br><br>

On the other hand, when we run `sort!(v)`, the contents of v are sorted within the array `v`.

In [63]:
sort!(v)

3-element Vector{Int64}:
 2
 3
 5

In [64]:
v

3-element Vector{Int64}:
 2
 3
 5

### Functions as arguments

Functions, like literally anything else in Julia, are objects that can be passed around like any other value. Including giving them as arguments to other functions. 

A typical application of this is with the `findall` and related functions, that find the indices of all elements in a collection that return `true` for a particular expression.

In [65]:
expression(x) = (x < 0.5) | (x > 1.5)
x = 0:0.1:2
valid_indices = findall(expression, x)

10-element Vector{Int64}:
  1
  2
  3
  4
  5
 17
 18
 19
 20
 21

## Broadcasting


Broadcasting is a convenient syntax for applying any function over the elements of an iterable input. I.e., the result is a new iterable whose elements is the function application of the elements of the input.

Broadcasting is done via the simple syntax of adding a dot `.` before the parenthesis in the function call: `g.(x)`.

In [66]:
h(x, y = 1) = x + y

h (generic function with 2 methods)

In [67]:
x = [1, 2, 3]
h.(x) # without 2nd argument, `h` is just `x + 1`

3-element Vector{Int64}:
 2
 3
 4

In [68]:
y = [1, 2, 3]
h.(x, y) # each element of `x` is added to the corresponding element of `y`

3-element Vector{Int64}:
 2
 4
 6

Let's now apply it to a vector `x`

In [69]:
x = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [70]:
h.(x)

3-element Vector{Int64}:
 2
 3
 4

Broadcasting can be useful when the number of operations is small and one can easily reason about the way the operations would be broadcasted across input(s). 

A typical example of broadcasting is to make an exponential range, which doesn't have a pre-made function in Julia:

In [71]:
exp_range = 10.0 .^ (-3:3)

7-element Vector{Float64}:
    0.001
    0.010000000000000002
    0.1
    1.0
   10.0
  100.0
 1000.0

*(notice that for infix operators (like `+, -`) the `.` is put before the operator)*

# Exercises - basics

**Important note for all exercises: when an exercise says _"use function `function_name` to do something"_, you need to first learn how to use the function. For this, you access the function's documentation string, using the help mode (type `?` or `@doc` in the Julia console and then type the function name)!**



## Counting nucleotides
Create a function that given a DNA strand (as a `String`, e.g. `"AGAGAGATCCCTTA"`) it counts how much of each nucleotide (A G T or C) is present in the strand and returns the result as a dictionary mapping the nucleotides to their counts. The function should throw an error (using the `error` function) if an invalid nucleotide is encountered. Test your result with `"ATATATAGGCCAX"` and `"ATATATAGGCCAA"`.

*Hint: Strings are iterables! They iterate over the characters they contain.*

In [72]:
strand1 = "ATATATAGGCCAX"
strand2 = "ATATATAGGCCAA"

"ATATATAGGCCAA"


## Hamming distance

Create a function that calculates the Hamming distance of two equal DNA strands, given as strings. This distance is defined by counting (sequentially) the number of non-equal letters in the two strands, e.g. `"ATA"` and `"ATC"` have distance of 1, while `"ATC"` and `"CAT"` have distance of 3. 

*Hint: this exercise has a one-liner solution, using the `zip` and `count` functions.*

## Babylonian square root
To get the square root of $y$ Babylonians used the algorithm $x_{n+1} = \frac{1}{2}(x_n + \frac{y}{x_n})$ iteratively starting from some value $x_0$ to converge to $x_n \to \sqrt{y}$ as $n\to \infty$. Implement this algorithm in a function `babylonian(y, ε, x0 = 1)` (default optional argument `x0`), that takes some convergence tolerance `ε` to compare with the built-in `sqrt(y)`. The function should return the steps it took to reach the square root value within given tolerance.

_Hint: for this exercise you only need a `while` code block without any other code structures such as `for, if, ...`._

## Fibonacci numbers
Using recursion (a function that calls itself) create a function that given an integer `n` it returns the `n`-th [Fibonacci number](https://en.wikipedia.org/wiki/Fibonacci_number). Apply it using `map` to the range `1:8` to get the result `[1,1,2,3,5,8,13]`.

---

# Multiple Dispatch

## What is Multiple Dispatch?

Some handy definitions
* **function**: the name of the "function / process" we are referring to.
* **method**: what actually happens when we call the function with a specific combination of input arguments.

*Dispatch* means that when a function call occurs, the language decides somehow which of the function *methods* have to be used. 

### No dispatch
In no dispatch, as in e.g. C, there is nothing to be decided. The method and the function are one and the same. 

### Single dispatch
In single dispatch, as in most object-oriented languages (like Python), it is possible for the same function name to have different methods:
```
array.set_size(args...)
axis.set_size(args...)
```
where `array` could be an instance of something from `numpy` while `axis` could come from `matplotlib`. Here the language dispatches the function `set_size`, depending on the first argument, which is `array` or `axis`. It is important to note that in most object oriented languages, the **method is a property of the type**. 

### Multiple dispatch
Here dispatch occurs based on the type of **every single function argument**, as in
```
set_size(a::Array, args...) = ...
set_size(a::Axis, args...) = ...
set_size(s, a::Array, args...) = ...
set_size(a::Array, b::Vector) = ...
set_size(a::Array, x::Real, y::Real, z::Real) = ...
```
etc. 

This means that multiple dispatch allows for exponentially more "expressive power", as one can use all arguments of the function to dispatch on.

### How it works

Keeping things simple, multiple dispatch follows one really basic rule: **the most specific method that is applicable to the input arguments is the one chosen!** 

Upon calling a function, Julia will try to find the method that is most specific across all arguments. This means that if a method is defined for both the abstract type combination, as well as the concrete type combination, Julia will always call the more concrete one. This rule also applies to e.g. parametric types, since `Vector{Float64}` is more specialized than `Vector` a method defined explicitly for `Vector{Float64}` is more specific. This rule also applies to unions, since `Float64` is more specialized than `Union{Float64, String}`.

Two important points:

1. **methods do not belong to the Types!**
2. **new methods can be defined *after* the Types have been defined!**

## A simple example

#### Defining some types

In [73]:
abstract type Animal end # this is an abstract type. a supertype of the below

struct Dog <: Animal   # this is a concrete type. a subtype of the above
    name::String
end

struct Cat <: Animal
    name::String
end

Now let's instantiate four animals

In [74]:
fido = Dog("Fido")
rex = Dog("Rex")
whiskers = Cat("Whiskers")
spotty = Cat("Spotty")

Cat("Spotty")

And finally, let's define some functions that take advantage of these `Animal` types, as well as multiple dispatch. Adding a method to a function is done by simply defining the function while also declaring the Types you add a method for:

In [75]:
function encounter(a::Animal, b::Animal)
    verb = meets(a, b)
    println("$(a.name) meets $(b.name) and $verb")
end

meets(a::Animal, b::Animal) = "passes by"

meets (generic function with 1 method)

Both of the above functions are defined on the abstract type level.

In [76]:
encounter(fido, rex)
encounter(fido, spotty)

Fido meets Rex and passes by
Fido meets Spotty and passes by


We now define more specific methods like so:

In [77]:
meets(a::Dog, b::Dog) = "sniffs"
meets(a::Dog, b::Cat) = "chases"
meets(a::Cat, b::Dog) = "hisses"
meets(a::Cat, b::Cat) = "slinks"

meets (generic function with 5 methods)

*(notice how the amount of methods of `meets` increased)*

In [78]:
encounter(fido, rex)
encounter(fido, whiskers)
encounter(whiskers, spotty)
encounter(spotty, rex)

Fido meets Rex and sniffs
Fido meets Whiskers and chases
Whiskers meets Spotty and slinks
Spotty meets Rex and hisses


## Simple extension of multiple dispatch
What if we get a third animal? Like a rabbit? It is easy to extend the system

In [79]:
struct Rabbit <: Animal
    name::String
end

meets(a::Dog, b::Rabbit) = "wiggles its tail"
meets(a::Rabbit, b::Cat) = "hides"

hops = Rabbit("Hops")

Rabbit("Hops")

In [80]:
encounter(rex, hops)
encounter(hops, whiskers)

Rex meets Hops and wiggles its tail
Hops meets Whiskers and hides


Of course, in the case where no specialized method exists, we get the default fallback we defined, as expected:

In [81]:
encounter(whiskers, hops)

Whiskers meets Hops and passes by


## Inspecting dispatch

To see how many methods a function has to it, and from which module they come, use `methods`:

In [82]:
methods(meets)

# 7 methods for generic function "meets" from Main:
 [1] meets(a::Rabbit, b::Cat)
     @ c:\Users\tsh371\Documents\julia-workshop\jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y314sZmlsZQ==.jl:6
 [2] meets(a::Dog, b::Rabbit)
     @ c:\Users\tsh371\Documents\julia-workshop\jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y314sZmlsZQ==.jl:5
 [3] meets(a::Cat, b::Cat)
     @ c:\Users\tsh371\Documents\julia-workshop\jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y310sZmlsZQ==.jl:4
 [4] meets(a::Cat, b::Dog)
     @ c:\Users\tsh371\Documents\julia-workshop\jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y310sZmlsZQ==.jl:3
 [5] meets(a::Dog, b::Cat)
     @ c:\Users\tsh371\Documents\julia-workshop\jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y310sZmlsZQ==.jl:2
 [6] meets(a::Dog, b::Dog)
     @ c:\Users\tsh371\Documents\julia-workshop\jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y310sZmlsZQ==.jl:1
 [7] meets(a::Animal, b::Animal)
     @ c:\Users\tsh371\Documents\julia-workshop\jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y303sZmlsZQ==.jl:6

To see which method is called on a function call signature, use `@which`:

In [83]:
@which meets(whiskers, rex)

meets(a::Cat, b::Dog)
     @ Main c:\Users\tsh371\Documents\julia-workshop\jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y310sZmlsZQ==.jl:3

*(in VSCode clicking that link would bring you to the source code where the method is defined; in Jupyter notebooks this feature doesn't work 🙁)*

In Julia, all "generic" functions are of equal "status". The function `+` is in no way superior, or with more privileges, than the function `meets` we wrote up.

It just has a bit more methods:

In [84]:
+

+ (generic function with 198 methods)

### Extending existing functions/types

I won't be going into Modules and namespaces here. But it is important to note that it would be possible for us to extend the `Animal` type as well as the `meets` function, *even if* they were coming from a different Module (e.g. a different Julia package).

Extension is identical with creating a new method, however one has to specify the parent module as well:

In [85]:
Base.:+(a::Animal, b::Animal) = println("$(a.name) and $(b.name) are animals")
Base.:+(a::Cat, b::Cat) = println("$(a.name) and $(b.name) cutie-cats, much cuter than doggos!")

In [86]:
rex + whiskers

Rex and Whiskers are animals


In [87]:
spotty + whiskers

Spotty and Whiskers cutie-cats, much cuter than doggos!
